FROM ghcr.io/openconext/openconext-basecontainers/php82-apache2:latest
ADD output.tar /var/www/html/

# Set the default workdir
WORKDIR /var/www/html
# Add the application configuration files
COPY config/openconext/parameters.yaml.dist config/openconext/parameters.yaml
COPY config/openconext/institutions.yaml.dist config/openconext/institutions.yaml
COPY config/packages/prod/monolog.yaml.docker config/packages/prod/monolog.yaml

# Add the config files for Apache2
RUN rm -rf /etc/apache2/sites-enabled/*
COPY ./docker/conf/azuremfa-apache2.conf /etc/apache2/sites-enabled/azuremfa.conf
RUN rm -rf /var/www/html/var/cache/prod && chown -R www-data /var/www/html/var
EXPOSE 80

CMD ["apache2-foreground"]
