FROM busybox AS unpack
WORKDIR /unpack
COPY output.zip /unpack
RUN unzip /unpack/output.zip

FROM ghcr.io/openconext/openconext-basecontainers/php82-apache2:latest
# Set the default workdir
WORKDIR /var/www/html
# Copy the files unpacked in stage unpack
COPY --from=unpack  /unpack/ /var/www/html/
# Add the application configuration files
COPY config/openconext/parameters.yaml.dist config/openconext/parameters.yaml
COPY config/openconext/institutions.yaml.dist config/openconext/institutions.yaml
COPY config/packages/prod/monolog.yaml.docker config/packages/prod/monolog.yaml

# Add the config files for Apache2
RUN rm -rf /etc/apache2/sites-enabled/* && rm -rf /var/www/html/output.zip
COPY ./docker/conf/azuremfa-apache2.conf /etc/apache2/sites-enabled/azuremfa.conf
RUN rm -rf /var/www/html/var/cache/prod && chown -R www-data /var/www/html/var
EXPOSE 80

CMD ["apache2-foreground"]
