# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl_NL

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $identityProviderCacheDir: '%federation_metadata_cache_location%'

    Surfnet\AzureMfa\:
        resource: '../src/Surfnet/AzureMfa/*'

    Surfnet\AzureMfa\Infrastructure\:
        resource: '../src/Surfnet/AzureMfa/Infrastructure/*'
        exclude: '../src/Surfnet/AzureMfa/Infrastructure/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Surfnet\AzureMfa\Infrastructure\Controller\:
        resource: '../src/Surfnet/AzureMfa/Infrastructure/Controller/*'
        tags: ['controller.service_arguments']

    Surfnet\AzureMfa\Infrastructure\Controller\ExceptionController:
        tags: ['controller.service_arguments']
        arguments:
            $errorPageHelper: '@Surfnet\AzureMfa\Infrastructure\Service\ErrorPageHelper'

    Surfnet\AzureMfa\Infrastructure\Institution\ConfigurationValidator:
        arguments:
            $configuration: '%institution_configuration%'

    Surfnet\AzureMfa\Infrastructure\Twig\GlobalViewParameters:
        arguments:
            $supportUrl: '%support_url%'
            $supportEmail: '%support_email%'

    Surfnet\AzureMfa\Application\Service\AuthenticationHelper:
        arguments:
            $regex: '%ra_issuer_entity_id_regex%'
